Repository dev-AshishRanjan/Idea-Arca, pull requests merged in 2023-10, with the labels that each got.

#18 Added simple chat app idea
  src/database/MainData.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, merge when passing, Idea-Arca, size/XS

#19 Update MainData.json for ML projects
  src/database/MainData.json
Labels: enhancement, hacktoberfest, Idea-Arca, idea, size/S

#20 I have added an Idea of resume maker
  src/database/MainData.json
Labels: hacktoberfest-accepted, hacktoberfest, merge when passing, Idea-Arca, idea, size/XS

#21 Added new project named "Emojicrypt" in "HTML CSS JS" Section
  src/database/MainData.json
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, idea, size/XS

#25 ADD : Data for Wordpress
  src/database/MainData.json
Labels: hacktoberfest-accepted, size/S

#28 Update MainData.json for a new idea
  src/database/MainData.json
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, approved, idea, size/XS

#30 Data for Augmented Reality (AR) section
  src/database/MainData.json
Labels: hacktoberfest-accepted, Idea-Arca, idea, size/S

#37 Red-range theme added
  src/components/ThemeSelector.astro
  src/styles/themes.scss
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, theme, size/S

#38 ADD idea : id 11
  src/database/MainData.json
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, idea, size/XS

#39 new idea related to AR
  src/database/MainData.json
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, idea, Extra Small, size/XS

#40 Added my theme greeny
  src/components/ThemeSelector.astro
  src/database/MainData.json
  src/styles/themes.scss
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, theme, Extra Small, size/M

#45 Update MainData.json with restaurant website and quiz app project idea
  src/database/MainData.json
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, idea, Extra Small, size/S

#46 adding new idea in wordpress
  src/database/MainData.json
Labels: hacktoberfest-accepted, merge when passing, Idea-Arca, idea, Extra Small, size/XS
